BlockchainRiskControlJob:
    Db:
        LogsConnString:
            settings-key: BlockchainRiskControlJob-LogsConnString
            types:
                - AzureTableStorage
        AzureDataConnString:
            settings-key: BlockchainRiskControlJob-AzureDataConnString
            types:
                - AzureTableStorage
        MongoDataConnString:
            settings-key: BlockchainRiskControlJob-MongoDataConnString
            types:
                - MongoDB
    Cqrs:
        RabbitConnectionString:
            settings-key: RabbitSagas
            types:
                - RabbitMq
        RetryDelay:
            settings-key: BlockchainRiskControlJob-RetryDelay
        WaitForOperationResolutionRetryDelay:
            settings-key: BlockchainRiskControlJob-WaitForOperationResolutionRetryDelay
    ConstraintsGroups:
        settings-key: BlockchainRiskControlJob-ConstraintsGroups
        types:
            - JsonArray
    Telegram:
        Token:
            settings-key: BlockchainRiskControlJob-Telegram-Token
        ChatId:
            settings-key: BlockchainRiskControlJob-Telegram-ChatId
    types: [Optional]
            types: [Optional]
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

